import streamlit as st
import google.generativeai as genai
import time
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
import re

# --- Konfigurasi Halaman ---
st.set_page_config(
    page_title="AI Lesson Plan Generator",
    page_icon="📚",
    layout="centered"
)

# --- Header sederhana ---
st.title("📚 AI Lesson Plan Generator")
st.caption("Powered by Google Gemini AI | Generate RPP berkualitas dengan muatan kearifan lokal Jawa Timur")

# --- Ambil API Key dari Streamlit Secrets ---
try:
    gemini_api_key = st.secrets["GEMINI_API_KEY"]
except:
    st.error("❌ API Key tidak ditemukan. Setup Secrets terlebih dahulu!")
    st.stop()

# --- Konfigurasi Gemini ---
MODEL_NAME = "gemini-2.5-flash"
genai.configure(api_key=gemini_api_key)

# --- Session State untuk menyimpan hasil ---
if 'generated_content' not in st.session_state:
    st.session_state.generated_content = None
if 'is_generated' not in st.session_state:
    st.session_state.is_generated = False
if 'current_topic' not in st.session_state:
    st.session_state.current_topic = ""

# --- Fungsi membuat file Word ---
def create_word_document(content, topic_name):
    doc = Document()
    
    # Margin
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Judul
    title = doc.add_heading('RENCANA PELAKSANAAN PEMBELAJARAN (RPP)', level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Topik: {topic_name}")
    doc.add_paragraph('_' * 50)
    
    # Bersihkan dan tambahkan konten
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            doc.add_paragraph()
        elif line.startswith('##'):
            doc.add_heading(line.replace('##', '').strip(), level=2)
        elif line.startswith('###'):
            doc.add_heading(line.replace('###', '').strip(), level=3)
        elif line.startswith('-') or line.startswith('*'):
            doc.add_paragraph(line[1:].strip(), style='List Bullet')
        else:
            # Hapus markdown bold
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
            doc.add_paragraph(clean_line)
    
    # Footer
    from datetime import datetime
    footer = doc.sections[0].footer
    footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    footer_para.text = f"Generated by AI Lesson Plan Generator | {datetime.now().strftime('%d/%m/%Y %H:%M')}"
    footer_para.style = doc.styles['Normal']
    footer_para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc_bytes = BytesIO()
    doc.save(doc_bytes)
    doc_bytes.seek(0)
    return doc_bytes

# --- Fungsi panggil Gemini ---
def call_gemini(prompt_text):
    model = genai.GenerativeModel(MODEL_NAME)
    
    for attempt in range(3):
        try:
            response = model.generate_content(
                prompt_text,
                generation_config={
                    "temperature": 0.7,
                    "max_output_tokens": 6000,
                }
            )
            content = response.text
            # Bersihkan markdown wrapper
            content = re.sub(r'^```\w*\n?', '', content)
            content = re.sub(r'\n?```$', '', content)
            return content.strip()
        except Exception as e:
            if attempt < 2 and ("503" in str(e) or "high demand" in str(e).lower()):
                time.sleep(2)
                continue
            st.error(f"Error: {str(e)}")
            return None

# --- Form Input ---
with st.form("lesson_form"):
    topic = st.text_area(
        "📖 **Topik Pembelajaran**",
        height=80,
        placeholder="Contoh: Memperkenalkan Tari Remo kepada siswa SD Kelas 5",
        help="Maksimal 100 kata"
    )
    
    col1, col2 = st.columns(2)
    with col1:
        language = st.selectbox("🌐 Bahasa", ["Indonesian", "English"], index=0)
        grade = st.text_input("🎓 Kelas", placeholder="Kelas 5 SD")
    with col2:
        std1 = st.text_area("🎯 Standar 1 (Capaian Pembelajaran)", height=60)
        std2 = st.text_area("📝 Standar 2 (Tujuan Pembelajaran)", height=60)
    
    time_allotment = st.text_input("⏰ Alokasi Waktu", placeholder="2 x 35 menit")
    
    submitted = st.form_submit_button("🚀 Generate Lesson Plan", use_container_width=True)

# --- Proses Generate ---
if submitted:
    if not topic.strip():
        st.error("Topik tidak boleh kosong!")
        st.stop()
    
    word_count = len(topic.split())
    if word_count > 100:
        st.error(f"Topik melebihi 100 kata! ({word_count} kata)")
        st.stop()
    
    # Simpan topic ke session
    st.session_state.current_topic = topic
    
    with st.spinner("AI sedang menyusun Rencana Pembelajaran..."):
        prompt = f"""
        Buat Rencana Pelaksanaan Pembelajaran (RPP) dengan detail berikut:
        
        Topik: {topic}
        Bahasa: {language}
        Kelas: {grade}
        Standar 1: {std1}
        Standar 2: {std2}
        Alokasi Waktu: {time_allotment}
        
        Integrasikan kearifan lokal Jawa Timur.
        
        Struktur:
        1. KOMPETENSI AWAL
        2. PROFIL PELAJAR PANCASILA
        3. KEGIATAN PEMBELAJARAN (Pendahuluan, Inti, Penutup)
        4. PENILAIAN
        
        Gunakan format:
        ## untuk judul utama
        ### untuk sub judul
        - untuk list
        **teks** untuk penekanan
        
        Langsung ke konten, tanpa kata pengantar.
        """
        
        result = call_gemini(prompt)
        
        if result:
            st.session_state.generated_content = result
            st.session_state.is_generated = True
            st.success("✅ Lesson Plan berhasil dibuat!")
        else:
            st.error("Gagal menghasilkan. Silakan coba lagi.")

# --- Tampilkan hasil jika ada ---
if st.session_state.is_generated and st.session_state.generated_content:
    st.divider()
    
    # Tombol download
    doc_file = create_word_document(
        st.session_state.generated_content, 
        st.session_state.current_topic[:50]
    )
    
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.download_button(
            label="📥 Download Lesson Plan (Word)",
            data=doc_file,
            file_name=f"Lesson_Plan_{int(time.time())}.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            use_container_width=True
        )
    
    st.divider()
    
    # Preview
    st.subheader("📄 Preview")
    st.markdown(st.session_state.generated_content)
    
    st.caption("💡 Preview hanya untuk dilihat. Download file Word untuk hasil cetak yang rapi.")
